---
title: "Getting started with R and Data"
output: html_document
---

```{r setup, include = FALSE, echo = FALSE}
knitr::opts_chunk$set(
    echo = TRUE,
    warn = FALSE,
    error = FALSE,
    include = TRUE,
    cache = FALSE
)
options(digits = 3)

library(tidyverse)
source('lib/credit_data_mapping.R')

```


## Transforming data in R

### The old way

```{r load_credit_data_base}
credit_data <- read.table(
    'data/credit_data.txt',
    sep  =  " ",
    stringsAsFactors = FALSE,
    header = FALSE
)
colnames(credit_data) <- credit_data_colnames
```

```{r transform_credit_data_base}

for(ci in colnames(credit_data)) {
    if(is.character(credit_data[[ci]])) {
        credit_data[[ci]] <- as.factor(credit_data_mapping[credit_data[[ci]]])
    }
}
credit_data$Good_Loan <- as.factor(ifelse(credit_data$Good_Loan == 1, 'GoodLoan', 'BadLoan'))
```

```{r summary_credit_data_base}
summary(credit_data)
```



### The tidy way

```{r load_credit_data_tidy}
read_delim(
    'data/credit_data.txt',
    delim = ' ',
    col_names = credit_data_colnames
) %>% 
    # map codes to their values and save as factors
    modify_if(is.character, ~factor(credit_data_mapping[.x])) %>% 
    # convert all numeric columns to integers
    modify_if(is.numeric, as.integer) %>% 
    rename(Loan = Good_Loan) %>% 
    mutate(
        # 1 is good, 2 is bad. Make 0 -> good, 1 -> bad
        Loan = factor(Loan - 1, labels = c('Good', 'Bad'))
    ) %>% 
    write_rds('data/credit_data.rds')
```


```{r load_credit_data}
credit_data <- read_rds('data/credit_data.rds')
credit_data %>% 
    count(Loan)

```

## Examining variable of interest

### Using `table`


```{r}
prop.table(table(credit_data$Purpose, credit_data$Loan), margin=1)
```

### The `tidy` way


```{r}
credit_data %>% 
    group_by(Purpose, Loan) %>% 
    summarise(n = n(), .groups = 'drop') %>%
    group_by(Purpose) %>%
    mutate(perc = n / sum(n)) %>% 
    ungroup() %>% 
    select(-n) %>% 
    pivot_wider(names_from = 'Loan', values_from = 'perc')
```


### Using `xtabs`

```{r}
prop.table(xtabs(~Purpose+Loan, data = credit_data), margin=1)
```



